### PR TITLE
Fix SelectMany

### PR DESCRIPTION
**Pull request by StefH**
-     moved source and test files into separate folder
-     fixed SelectMany definition + code to be 100% compatible with C# `Enumerable.SelectMany(...)`
-     used chutzpah + qunit(TypeScript.DefinitelyTyped) as Typescript test runner (can also be used in vs2015)
-     rewrote all tests to use qunit
-     added tests for the updaterd SelectMany

### CODE REVIEW

**Comment by StefH** [comment]
I see that this branch has conflicts (due to the merge from @terryaney), so I will merge the latest from aster into my branch and do create a new pull request.

**Comment by StefH** [comment]
Branch is up-to-date, merge can be done automatically.

**Comment by terryaney** [comment]
Hope I didn’t mess anything up to cause the hassle.

**Comment by StefH** [comment]
No, the merge was ok.

**Comment by StefH** [comment]
Any update on merging my code ?

**Comment by StefH** [comment]
@terryaney Any update?

**Comment by terryaney** [comment]
Hmm, guess I saw your 'No, the merge was ok.' comment and didn't see rest of this thread.  What are you waiting on?  Or what can I do?

**Comment by StefH** [comment]
You need to merge my pull request to your code branch.

And if needed publish your library to npm or another repository.

**Comment by terryaney** [comment]
I don't have rights to do a merge on this repo.  I only changed one line of code.  You can see the commit here: https://github.com/brunolm/TSLinq/commit/0c222de2d35bb6bd63429568ad3e3297fcca67b6

But I think @brunolm has to accept your pull request.

**Comment by StefH** [comment]
@brunolm Can you please check ?

**Comment by brunolm** [comment]
Actually I don't know what to do with this project. It is not solid enough to use in production, it was more something I did for fun.

I think I will just keep it as is, and maybe add this note on the README.

**Comment by terryaney** [comment]
Yikes ;)  I'm using in production.  Not stressing it too hard obviously, but just made porting C# code to JS/TS easier to be able to do the same Where/Select/FirstOrDefault extensions.  Thanks.

**Comment by brunolm** [comment]
It is not like it is completely broken, but it doesn't have enough tests and more complex cases. For basic usage I think it is fine.

**Comment by StefH** [comment]
Please accept my pr. Tests are fine.

**Pull request closed without merging**
